package com.jookmax.v7.brain.pipeline


import com.jookmax.v7.brain.decision.DecisionResult



/**
 * Represents complete output of one brain execution cycle.
 *
 * Contains:
 * - Full analysis context
 * - Final trading decision
 *
 * Used for:
 * - Decision analytics
 * - Learning system
 * - Debugging
 * - Future backtesting
 */
data class BrainExecutionResult(


    /**
     * Complete brain state during execution.
     */
    val context: BrainContext,



    /**
     * Final decision generated by DecisionEngine.
     */
    val decision: DecisionResult


)