package com.jookmax.v7.brain.pipeline


import com.jookmax.v7.brain.decision.DecisionResult
import com.jookmax.v7.brain.market.MarketAnalysis
import com.jookmax.v7.brain.risk.RiskResult



data class BrainContext(


    val marketAnalysis: MarketAnalysis,


    val riskResult: RiskResult,


    val learningReward: Double,


    /**
     * Final decision generated by DecisionEngine.
     *
     * Nullable because context is created
     * before decision generation.
     */
    val decisionResult: DecisionResult? = null


)